<?xml version="1.0" encoding="utf-8"?><Database Name="CloudDb" Class="DBContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=localhost;Initial Catalog=DataExplorer;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="AppConnection" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CachedResults" Member="CachedResults">
    <Type Name="CachedResult">
      <Column Name="QueryHash" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SiteId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Results" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.QueryExecutions" Member="QueryExecutions">
    <Type Name="QueryExecution">
      <Column Name="Id" AutoSync="Never" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="QueryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SiteId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FirstRun" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="LastRun" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ExecutionCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Users" Member="Users">
    <Type Name="User">
      <Column Name="Id" AutoSync="Never" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Login" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="LastLogin" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsAdmin" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IPAddress" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="IsModerator" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AboutMe" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Website" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Location" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DOB" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastActivityDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastSeenDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="User_Query" Member="Queries" ThisKey="Id" OtherKey="CreatorId" Type="Query" />
      <Association Name="User_SavedQuery" Member="SavedQueries" ThisKey="Id" OtherKey="UserId" Type="SavedQuery" />
      <Association Name="User_UserOpenId" Member="UserOpenIds" ThisKey="Id" OtherKey="UserId" Type="UserOpenId" />
    </Type>
  </Table>
  <Table Name="dbo.Sites" Member="Sites">
    <Type Name="Site">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TinyName" Type="System.String" DbType="NVarChar(12) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="LongName" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="Url" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ImageUrl" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="IconUrl" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="DatabaseName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Tagline" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="TagCss" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="TotalQuestions" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalAnswers" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalUsers" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalComments" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalTags" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastPost" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Site_SavedQuery" Member="SavedQueries" ThisKey="Id" OtherKey="SiteId" Type="SavedQuery" />
    </Type>
  </Table>
  <Table Name="dbo.Queries" Member="Queries">
    <Type Name="Query">
      <Column Name="Id" AutoSync="Never" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="QueryHash" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="QueryBody" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CreatorId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatorIP" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="FirstRun" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Views" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Association Name="Query_SavedQuery" Member="SavedQueries" ThisKey="Id" OtherKey="QueryId" Type="SavedQuery" />
      <Association Name="User_Query" Member="User" ThisKey="CreatorId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SavedQueries" Member="SavedQueries">
    <Type Name="SavedQuery">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="QueryId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SiteId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LastEditDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsFeatured" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsSkipped" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsDeleted" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="FavoriteCount" Type="System.Int32" DbType="Int" CanBeNull="false" />
      <Column Name="IsFirst" Type="System.Boolean" DbType="bit" CanBeNull="false" />
      <Association Name="User_SavedQuery" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
      <Association Name="Site_SavedQuery" Member="Site" ThisKey="SiteId" OtherKey="Id" Type="Site" IsForeignKey="true" />
      <Association Name="Query_SavedQuery" Member="Query" ThisKey="QueryId" OtherKey="Id" Type="Query" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Votes" Member="Votes">
    <Type Name="Vote">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SavedQueryId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="VoteTypeId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CreationDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.UserOpenId" Member="UserOpenIds">
    <Type Name="UserOpenId">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OpenIdClaim" Type="System.String" DbType="NVarChar(450)" CanBeNull="true" />
      <Association Name="User_UserOpenId" Member="User" ThisKey="UserId" OtherKey="Id" Type="User" IsForeignKey="true" />
    </Type>
  </Table>
</Database>